
# Site settings

#############
# HTML Head #
#############

author: "Francisco Portillo"
url: "http://portillo.blog.br"
lang: "en"
title: "{ Francisco Portillo }"
description: "Olá pessoal, esse é meu espaço na web. Aqui você encontra de tudo um pouco sobre mim :)."
keywords: "smith, jones, personal, jekyll, theme"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
404-img: "/img/labtocat.png"

google-tracking-id: "<YOUR GOOGLE TRACKING ID>"


################
# About layout #
################

background-img: "../img/intro-bg.jpg"
me-img: "/img/chiconavypeer.png"

########
# Blog #
########

# Number of words shown in the latest post preview, in the index

post-preview-words: 128

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "<YOUR DISQUS USERNAME>"

###############
# Life Events #
###############

events:
  - image: "/img/career/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/career/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/fportillo"
  - title: "linkedin"
    url: "http://br.linkedin.com/in/fportillo"
  - title: "twitter"
    url: "https://twitter.com/portillof"
  - title: "rss"
    url: "/feed.xml"

##################
# Contact layout #
##################

email: "francisco.portillo@gmail.com"

# Tread carefully if you want to change the variables bellow this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  Sobre: 'sobre'
  Blog: 'blog'
  Xp: 'xp'
  Contato: 'contato'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
